### ISSUE TITLE
How long will it take to repair the servers?

### ISSUE THREAD

**Issue by 101Corp** [Scratchblox-Official/scratchblox#10] opened 2021-05-19 02:25 UTC
The servers are returning “inaccessible” on log in and sign up.
Are the servers off? If they are, when will the site be restarted? If it’s a rebuild, when will the site be back up?

**Comment by Turtle84375** [comment] 2021-05-19 03:46
@Ancoder2009 has these answers.

See #1 for some information.

Duplicate of #9, I'll leave this marked as open so people don't keep asking this question.

**Closed** 2021-05-21 17:32 UTC
Labels: bug, duplicate, in progress
